### ISSUE TITLE
Registrations older than 30 days are not recognized

### ISSUE THREAD

**Issue by ssalzillo** [merrill-oakland/moodle-mod_webexactivity#13]
Hi,
seems that plugin can't find registrations that are older than 30 days.
It's a webex limitation?
Thanks for your work

**Comment by merrill-oakland** [comment]
Can you be more specific about what you are seeing, I'm not sure what you specifically mean.

It might be on WebEx's side - there have been some things that recently we have noticed them disappearing from webex after a certain amount of time.

**Comment by barry-matthias** [comment]
hi when webex runs its cron processes specifically \mod_webexactivity\task\update_medium_recordings it throws an exception as per below 
Scheduled task failed: Update medium past recordings (mod_webexactivity\task\update_medium_recordings),An error occurred in WebEx while processing XML: 999999 Maximum querying date range is 28 days.
This seems to be a limitation on the webex server not allowing the lms module to query recordings which are older than 28 days from the time the recording was started?

**Comment by merrill-oakland** [comment]
What version of the plugin are you using? This was fixed in 3.4.0 and 3.1.2 (depending on the version of Moodle you are using)

**Comment by barry-matthias** [comment]
we are currently using 3.3.0 2017060600 webexmeeting module as per blackboard/moodlerooms hosted codebase should we upgrade to 3.4.0 too correct this issue ?

**Comment by merrill-oakland** [comment]
Yes, moving to 3.4.0 will fix this problem.
