### ISSUE TITLE
Remote participants link may be wrong

### ISSUE THREAD

**Issue by merrill-oakland** [merrill-oakland/moodle-mod_webexactivity#15]
Got a note from José González that when using the Remote Participants link may be incorrect. He reports that it asks for a meeting ID when you try to use it.

Need to test it out.

**Comment by merrill-oakland** [comment]
Testing finds that the link work fine for Training Center, but it fails for Meeting Center, taking you to a 'enter meeting id' page.

**Comment by Joe-GM** [comment]
Hello @merrill-oakland  I did again a test, but Now I started the Meeting Center befor to Join the external Link.
And It's works good.

Thanks!

**Comment by merrill-oakland** [comment]
The next release is including some additional changes to how the external participants link is created.
