### ISSUE TITLE
Moodle 3.5 Plugin Install

### ISSUE THREAD

**Issue by WKupper** [merrill-oakland/moodle-mod_webexactivity#16]
When attempting to install the plugin on a Moodle 3.5.4 I get the following error:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 3415539904709949512 bytes) in /opt/websites/moodle/xxxx/lib/dml/moodle_database.php on line 484

**Comment by merrill-oakland** [comment]
I'm not sure what is happening here. I can't recreate it off hand. What DB are you using, and what version of PHP?

Even the error itself is a bit nonsensical, as the line called out isn't a link that is doing anything - especially not allocating memory:

```php
         switch ($type) {
>            case SQL_QUERY_SELECT:
             case SQL_QUERY_AUX:
                 throw new dml_read_exception($error, $sql, $params);
             case SQL_QUERY_INSERT:
```
