### ISSUE TITLE
how to use webex on moodle 3.5

### ISSUE THREAD

**Issue by sulaganathan** [merrill-oakland/moodle-mod_webexactivity#17]
Where do I see manual of how to use webex on Moodle 3.5 as external tool?

**Comment by merrill-oakland** [comment]
I'm not sure what you mean.

This is a plugin for Moodle, and is unrelated to the new LTI (External Tool) integration from Cisco.

If that is what you are looking for, you probably want this:
https://help.webex.com/en-us/n77zrcq/Install-the-Cisco-Webex-Education-Connector-in-Your-Learning-Management-System
