### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by collegemathieu** [merrill-oakland/moodle-mod_webexactivity#2]
Good morning!
Was just wondering if this plugin was still in development and if you would welcome other contributer?
We really want to use our Webex solution with our Moodle and this seems to be the best place to start.

**Comment by merrill-oakland** [comment]
Yup, I'm still maintaining this, just haven't had a lot of time recently to do much. Need to bundle it up for Moodle 3.0 (although it does work). We are always happy to accept contributions!
