### ISSUE TITLE
Manage recordings - delete recording from Moodle but not from Webex Cloud

### ISSUE THREAD

**Issue by al-bras** [merrill-oakland/moodle-mod_webexactivity#25]
Dear all,

I clicked the manage recordings button, and now all the recordings of the Webex Cloud are in Moodle. I do not want to have them. How can I delete them without deleting them from Webex Cloud?

Thanks for your help!

Best,
Alex

**Comment by ericmerrill** [comment]
If you turn off manage all, you can remove the extras with something like this in the DB:
`DELETE FROM mdl_webexactivity_recording WHERE webexid IS NULL;`

**Comment by al-bras** [comment]
Thanks a lot!
