### ISSUE TITLE
Participants wants to join a meeting. URL blocked

### ISSUE THREAD

**Issue by al-bras** [merrill-oakland/moodle-mod_webexactivity#26]
Hi, whenever I join a meeting the URL is blocked. If I go back and try again, it works. Do you know why this could be the case?
Thanks a lot for your help.

**Comment by ericmerrill** [comment]
If you are getting a url blocked error, then you likely need to contact Webex support and have them add your Moodle domain to the allowed URL API and/or redirect domains.

**Comment by al-bras** [comment]
Thanks a lot! Found the solution here: https://moodle.org/mod/forum/discuss.php?d=255736&parent=1592077
