### ISSUE TITLE
Error when starts a sesion like host

### ISSUE THREAD

**Issue by tredevelop** [merrill-oakland/moodle-mod_webexactivity#29]
When starting sessions from Moodle as a host, the following error is returned:
Error occurred in Webex processing: 060002 An in-progress session cannot be updated or deleted.
 
This error occurs in the following situations:

1. An attendee/student is inside the Webex session and attempts to join a different host/teacher than the teacher who edited/created the session. Both teachers are registered in Webex. If no students are logged in to Webex, then it does allow the teacher who did not edit/create the event normally to host.
2. The host / teacher is already in the session and tries to enter another teacher as host. Both teachers are registered in Webex.

The teacher cannot log in as a host to webex in any of the situations described above.

**Comment by rcaeiro** [comment]
After commenting with the Webex people they tell us the following, for which it would be necessary to update the plugin, to avoid this problem.

If there are multiple instructors in one course, each instructor will only be able to start, edit, and delete the meetings that they created, and will not be able to do so for meetings created by other instructors.
The internal documentation from webex was last updated on December 27th 2021

1.           Only the instructor who has created the meeting can host the meeting, and no other instructor enrolled in the same course can host the meeting he hasn't created. Only the instructor who has created the meeting will be able to see "Start, Edit, Delete" option in front of the meeting he has created, whereas, all the other instructors will only see the "Join" option.
2.           As per above, the new teacher should see the “Join” option to enter the meeting started by the original host.
